[package]
name = "ruscheme"
version = "0.1.0"
authors = ["Pietrino Atzeni <pietrino.atzeni@moneyfarm.com>"]
edition = "2018"

[dependencies]
colored = "*"
log = "*"
env_logger = "*"
crossterm = "*"
regex = "*"

[dev-dependencies]
hamcrest2 = "*"

[features]
default = []

compiler = []
